freebsd_instance:
  image_family: freebsd-15-0

task:
  name: FreeBSD
  env:
    IGNORE_OSVERSION: yes
  skip_notifications: true
  prerequisites_script:
    - pkg update -f
    - pkg upgrade -y
    - pkg install -y devel/git devel/pkgconf graphics/vips www/node22 www/npm
    - pkg-config --modversion vips-cpp
  install_script:
    - npm install
    - npm run build
  test_script:
    - node --test test/unit/io.js
